baseurl = "/"
title = "RLC (Team 13)"
copyright = "Copyright (c) 2020, all rights reserved."
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

[author]
  name = "RLC"

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "rrt" # dark themes: monokai, api, fruity, native, rrt, swapoff

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Downloads"
  weight = -100
  identifier = "downloads"
  url = "/downloads/"

[[menu.main]]
  name = "Docs"
  weight = 110
  identifier = "docs"
  url = "/docs/"



[params.meta]
  keywords = "tech, education"
  description = "Project Website"

[params]
  github = "orgs/Team-13-RLC/"
  gitlab = ""
  twitter = ""
  linkedin = ""
  email = "dk949@york.ac.uk"
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css

## Uncomment to be able to use raw HTML in md documents
#[markup.goldmark.renderer]
#  unsafe= true
